### PR TITLE
[FE unification] (Mid-Sr dev) Challenge for Adjust Frontend Developer 

### PR DESCRIPTION
**Pull request by AragonCodes**
## Description
Following our agreements from the "fe-unified-pipeline" slack channel, we will use this repo to test Jr devs.

Please review: 
1. README
2. `src`
3. `src/tests`
4.  A solved repo looks like [the one mentioned in Slack comment](https://adjust.slack.com/archives/C02A7JVEHP0/p1636127511004400)

## TODOs
- [x] define `contact` email (maybe frontend-hiring@adjust.com?)
- [x] define `frontend-hiring-github-user` GitHub account to evaluate candidates submissions

### CODE REVIEW

**Review by Sc4ramouche — APPROVED** [review]
Very nice set of tests 👍 
I think description provides enough guidance without specifying all the details, good job.

**Review by paul-pro — APPROVED** [review]
LGTM, let's wait for others

Small thing: @AragonCodes do we want to wipe git history for this repo somehow? So candidates wouldn't be distracted by it

**Comment by AragonCodes** [comment]
Please take a look 🙏🏻  @moktin @plachintas @lemanchester @PetrusStarken

**Comment by AragonCodes** [comment]
@BrunoAzzi thanks for reviewing the Jr challenge. Please take a look into this one which includes a React task as well

**Review by adrianlemess — APPROVED** [review]
LGTM

Also really nice the tests setup 😅

**Review by plachintas — APPROVED** [review]

**Pull request merged**
